---
version: "2.4"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Europe/Madrid
       #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    network_mode: "host"    
    volumes:
      - /home/pi/apps/config/jellyfin/config:/config
      - /home/pi/apps/config/jellyfin/cache:/cache
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /srv/dev-disk-by-uuid-79dac600-16b0-40ad-b9db-48cdb6916706/Series:/data/Series
      - /srv/dev-disk-by-uuid-79dac600-16b0-40ad-b9db-48cdb6916706/Peliculas:/data/Peliculas
      - /srv/dev-disk-by-uuid-79dac600-16b0-40ad-b9db-48cdb6916706/Musica:/data/Musica
    ports:
      - 8096:8096
        # - 8920:8920 #optional
        # - 7359:7359/udp #optional
        # - 1900:1900/udp #optional
    restart: unless-stopped
      #networks:
      #jmz_net:

      #networks:
      #jmz_net:
      #name: jmz_networks
      #driver: bridge
