---
version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin
#    container_name: jellyfin
    user: 1000:1000
    environment:
#      - PUID=1000
#      - PGID=1000
      - TZ=Europe/Madrid
      - ROC_ENABLE_PRE_VEGA=1
       #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    network_mode: 'host'    
    volumes:
      - ${config}/jellyfin:/config
      - ${config}/jellyfin/cache:/cache
      - ${HDD}/Series:/data/Series
      - ${HDD}/Peliculas:/data/Peliculas
      - ${HDD}/Musica:/data/Musica
    ports:
      - 8096:8096
        # - 8920:8920 #optional
        # - 7359:7359/udp #optional
        # - 1900:1900/udp #optional
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/kfd:/dev/dri/kfd
    group_add:
      - "106"
      - "44"
      #networks:
      #jmz_net:

      #networks:
      #jmz_net:
      #name: jmz_networks
      #driver: bridge
